name: GitHub Actions Build Spring Boot Application Demo
run-name: Try to build spring boot application with gradle.
on: [push]
  
jobs:
  Setting-JDK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '21'
          
  Build-Spring-Boot-Application:
    needs: Setting-JDK
    runs-on: ubuntu-latest
    steps:
    - name: list the files
      run: ls 
      working-directory: ./
    - name: Use gradle pulgin build jar
      run: ./gradlew bootJar
    - name: list the generated jar
      run: ls ./build/libs
